apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website
bases:
- ../workload
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: a5a07c5-202108240359 # {"$imagepolicy": "platform-website:platform-website:tag"}
