apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website
bases:
- ../workload
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: b1b2a63-202106292235 # {"$imagepolicy": "platform-website:platform-website:tag"}
